### ISSUE TITLE
askbot-devel clash

### ISSUE THREAD

**Issue by andreav** [dcramer/django-ratings#54]
I'm installing askbot-devel as an additional app in a project already containing django-ratings.
Django version is 1.8
When I run runserver, I get this error:

```
SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
askbot.Vote.user: (fields.E304) Reverse accessor for 'Vote.user' clashes with reverse accessor for 'Vote.user'.
    HINT: Add or change a related_name argument to the definition for 'Vote.user' or 'Vote.user'.
askbot.Vote.user: (fields.E305) Reverse query name for 'Vote.user' clashes with reverse query name for 'Vote.user'.
    HINT: Add or change a related_name argument to the definition for 'Vote.user' or 'Vote.user'.
djangoratings.Vote.user: (fields.E304) Reverse accessor for 'Vote.user' clashes with reverse accessor for 'Vote.user'.
    HINT: Add or change a related_name argument to the definition for 'Vote.user' or 'Vote.user'.
djangoratings.Vote.user: (fields.E305) Reverse query name for 'Vote.user' clashes with reverse query name for 'Vote.user'.
    HINT: Add or change a related_name argument to the definition for 'Vote.user' or 'Vote.user'.
```

Do you know a way to solve it?

Related issue is [#559](https://github.com/ASKBOT/askbot-devel/issues/559)
